<?php
require_once __DIR__ . '/../config.php'; require_once __DIR__ . '/../lib/layout.php';
requiere_login('../'); $pdo=db(); $msg=null;
$gestiona=tiene_rol(['SUPER_ADMIN','ADMIN','DIRECTOR','GERENCIA','CEO','CONTABILIDAD','ANALISTA']);
$pdo->exec("CREATE TABLE IF NOT EXISTS contabilidad_integraciones (id INTEGER PRIMARY KEY CHECK(id=1), siesa_url TEXT, siesa_token TEXT, banco_url TEXT, banco_token TEXT, modo TEXT DEFAULT 'MANUAL', actualizado_por TEXT, actualizado_en TEXT DEFAULT CURRENT_TIMESTAMP)");
$pdo->exec("CREATE TABLE IF NOT EXISTS contabilidad_auditoria (id INTEGER PRIMARY KEY AUTOINCREMENT, entidad TEXT, entidad_id INTEGER, accion TEXT, detalle TEXT, usuario TEXT, creado_en TEXT DEFAULT CURRENT_TIMESTAMP)");
if($_SERVER['REQUEST_METHOD']==='POST' && $gestiona){
 $a=$_POST['accion']??''; $u=usuario_actual()['nombre']??'Sistema';
 if($a==='cierre'){$sid=(int)$_POST['sede_id'];$fecha=trim($_POST['fecha']);$ventas=(float)$_POST['ventas'];$ef=(float)$_POST['efectivo'];$tar=(float)$_POST['tarjetas'];$tra=(float)$_POST['transferencias'];$otr=(float)$_POST['otros'];$total=$ef+$tar+$tra+$otr;$dif=$total-$ventas;
  $pdo->prepare("INSERT INTO cierres_tienda_contables(sede_id,fecha_cierre,ventas,efectivo,tarjetas,transferencias,otros,total_declarado,diferencia,estado,observaciones,creado_por) VALUES(?,?,?,?,?,?,?,?,?,'PENDIENTE',?,?) ON CONFLICT(sede_id,fecha_cierre) DO UPDATE SET ventas=excluded.ventas,efectivo=excluded.efectivo,tarjetas=excluded.tarjetas,transferencias=excluded.transferencias,otros=excluded.otros,total_declarado=excluded.total_declarado,diferencia=excluded.diferencia,observaciones=excluded.observaciones,estado='PENDIENTE'")->execute([$sid,$fecha,$ventas,$ef,$tar,$tra,$otr,$total,$dif,limpio($_POST['observaciones']??''),$u]);$msg=['ok','Cierre guardado y pendiente de revisión.'];
 }elseif($a==='pago'){$pdo->prepare("INSERT INTO programacion_pagos(proveedor,nit,concepto,factura,fecha_vencimiento,valor,medio_pago,estado,observaciones,creado_por) VALUES(?,?,?,?,?,?,?,'PROGRAMADO',?,?)")->execute([limpio($_POST['proveedor']),limpio($_POST['nit']),limpio($_POST['concepto']),limpio($_POST['factura']),$_POST['vencimiento'],(float)$_POST['valor'],limpio($_POST['medio']),limpio($_POST['observaciones']??''),$u]);$msg=['ok','Pago programado correctamente.'];
 }elseif($a==='estado'){$id=(int)$_POST['id'];$estado=strtoupper($_POST['estado']);if(in_array($estado,['APROBADO','OBSERVADO','PAGADO','ANULADO'],true)){$pdo->prepare("UPDATE programacion_pagos SET estado=?, aprobado_por=CASE WHEN ?='APROBADO' THEN ? ELSE aprobado_por END, aprobado_en=CASE WHEN ?='APROBADO' THEN CURRENT_TIMESTAMP ELSE aprobado_en END, pagado_en=CASE WHEN ?='PAGADO' THEN CURRENT_TIMESTAMP ELSE pagado_en END WHERE id=?")->execute([$estado,$estado,$u,$estado,$estado,$id]);$msg=['ok','Estado actualizado.'];}}
 elseif($a==='integracion'){$pdo->prepare("INSERT INTO contabilidad_integraciones(id,siesa_url,siesa_token,banco_url,banco_token,modo,actualizado_por) VALUES(1,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET siesa_url=excluded.siesa_url,siesa_token=excluded.siesa_token,banco_url=excluded.banco_url,banco_token=excluded.banco_token,modo=excluded.modo,actualizado_por=excluded.actualizado_por,actualizado_en=CURRENT_TIMESTAMP")->execute([limpio($_POST['siesa_url']),limpio($_POST['siesa_token']),limpio($_POST['banco_url']),limpio($_POST['banco_token']),limpio($_POST['modo']),$u]);$msg=['ok','Configuración guardada. Las integraciones quedan listas para conectar manualmente.'];}
}
$sedes=$pdo->query("SELECT id,nombre FROM sedes ORDER BY nombre")->fetchAll(PDO::FETCH_ASSOC);$cierres=$pdo->query("SELECT c.*,s.nombre sede FROM cierres_tienda_contables c LEFT JOIN sedes s ON s.id=c.sede_id ORDER BY fecha_cierre DESC LIMIT 30")->fetchAll(PDO::FETCH_ASSOC);$pagos=$pdo->query("SELECT * FROM programacion_pagos ORDER BY fecha_vencimiento LIMIT 30")->fetchAll(PDO::FETCH_ASSOC);$int=$pdo->query("SELECT * FROM contabilidad_integraciones WHERE id=1")->fetch(PDO::FETCH_ASSOC)?:[]; layout_inicio('Contabilidad operativa','modules/contabilidad_operativa.php','../');
if($msg) echo '<div class="alert '.e($msg[0]).'">'.e($msg[1]).'</div>'; ?>
<h1>Contabilidad operativa</h1><p class="small">Cierres de tiendas, conciliación interna y programación de pagos. Las conexiones externas se configuran manualmente.</p>
<div class="grid-2"><section class="card"><h2>Registrar cierre de tienda</h2><form method="post"><input type="hidden" name="accion" value="cierre"><label>Sede<select name="sede_id" required><?php foreach($sedes as $s) echo '<option value="'.(int)$s['id'].'">'.e($s['nombre']).'</option>'; ?></select></label><label>Fecha<input type="date" name="fecha" value="<?=date('Y-m-d')?>" required></label><label>Ventas sistema<input type="number" step="0.01" name="ventas" required></label><label>Efectivo<input type="number" step="0.01" name="efectivo" value="0"></label><label>Tarjetas<input type="number" step="0.01" name="tarjetas" value="0"></label><label>Transferencias<input type="number" step="0.01" name="transferencias" value="0"></label><label>Otros<input type="number" step="0.01" name="otros" value="0"></label><label>Observaciones<textarea name="observaciones"></textarea></label><button class="btn btn-primary">Guardar cierre</button></form></section>
<section class="card"><h2>Programar pago</h2><form method="post"><input type="hidden" name="accion" value="pago"><label>Proveedor<input name="proveedor" required></label><label>NIT<input name="nit"></label><label>Concepto<input name="concepto" required></label><label>Factura<input name="factura"></label><label>Vencimiento<input type="date" name="vencimiento" required></label><label>Valor<input type="number" step="0.01" name="valor" required></label><label>Medio<select name="medio"><option>TRANSFERENCIA</option><option>PSE</option><option>CHEQUE</option></select></label><label>Observaciones<textarea name="observaciones"></textarea></label><button class="btn btn-primary">Programar pago</button></form></section></div>
<section class="card"><h2>Integraciones manuales</h2><form method="post" class="grid-2"><input type="hidden" name="accion" value="integracion"><label>URL Siesa<input name="siesa_url" value="<?=e($int['siesa_url']??'')?>"></label><label>Token Siesa<input type="password" name="siesa_token" value="<?=e($int['siesa_token']??'')?>"></label><label>URL banco<input name="banco_url" value="<?=e($int['banco_url']??'')?>"></label><label>Token banco<input type="password" name="banco_token" value="<?=e($int['banco_token']??'')?>"></label><label>Modo<select name="modo"><option value="MANUAL">Manual / archivos</option><option value="API">API habilitada</option></select></label><button class="btn btn-primary">Guardar configuración</button></form></section>
<section class="card"><h2>Últimos cierres</h2><table><tr><th>Fecha</th><th>Sede</th><th>Ventas</th><th>Declarado</th><th>Diferencia</th><th>Estado</th></tr><?php foreach($cierres as $c) echo '<tr><td>'.e($c['fecha_cierre']).'</td><td>'.e($c['sede']??'').'</td><td>$'.number_format($c['ventas'],0,',','.').'</td><td>$'.number_format($c['total_declarado'],0,',','.').'</td><td>$'.number_format($c['diferencia'],0,',','.').'</td><td>'.e($c['estado']).'</td></tr>'; ?></table></section>
<section class="card"><h2>Programación de pagos</h2><table><tr><th>Proveedor</th><th>Factura</th><th>Vence</th><th>Valor</th><th>Estado</th><th>Acción</th></tr><?php foreach($pagos as $p){echo '<tr><td>'.e($p['proveedor']).'</td><td>'.e($p['factura']).'</td><td>'.e($p['fecha_vencimiento']).'</td><td>$'.number_format($p['valor'],0,',','.').'</td><td>'.e($p['estado']).'</td><td><form method="post"><input type="hidden" name="accion" value="estado"><input type="hidden" name="id" value="'.(int)$p['id'].'"><select name="estado"><option>APROBADO</option><option>PAGADO</option><option>OBSERVADO</option><option>ANULADO</option></select><button>Actualizar</button></form></td></tr>';} ?></table></section><?php layout_fin();
