<?php
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../lib/layout.php';
require_once __DIR__ . '/../lib/gobierno_operativo.php';
requiere_roles(['SUPER_ADMIN','ADMIN','DIRECTOR','GERENCIA','CEO','COORDINADOR','ANALISTA'], '../');
$pdo = db();
$area = alcance_area();
$cond = $area !== null ? ' WHERE s.area_responsable=' . $pdo->quote($area) : '';
$and = $area !== null ? ' AND s.area_responsable=' . $pdo->quote($area) : '';
$pendientes = (int)$pdo->query("SELECT COUNT(*) FROM solicitudes_aprobacion s WHERE s.estado='PENDIENTE'{$and}")->fetchColumn();
$vencidas = (int)$pdo->query("SELECT COUNT(*) FROM solicitudes_aprobacion s WHERE s.estado='PENDIENTE' AND s.fecha_limite<datetime('now'){$and}")->fetchColumn();
$montoPendiente = (float)$pdo->query("SELECT COALESCE(SUM(s.monto),0) FROM solicitudes_aprobacion s WHERE s.estado='PENDIENTE'{$and}")->fetchColumn();
$cerradas30 = (int)$pdo->query("SELECT COUNT(*) FROM solicitudes_aprobacion s WHERE s.estado IN('APROBADA','RECHAZADA') AND s.resuelto_en>=datetime('now','-30 days'){$and}")->fetchColumn();
$aprobadas30 = (int)$pdo->query("SELECT COUNT(*) FROM solicitudes_aprobacion s WHERE s.estado='APROBADA' AND s.resuelto_en>=datetime('now','-30 days'){$and}")->fetchColumn();
$tasa = $cerradas30 ? round($aprobadas30 / $cerradas30 * 100) : 0;
$tiempo = (float)$pdo->query("SELECT COALESCE(AVG((julianday(s.resuelto_en)-julianday(s.creado_en))*24),0) FROM solicitudes_aprobacion s WHERE s.resuelto_en IS NOT NULL{$and}")->fetchColumn();
$porArea = $pdo->query("SELECT s.area_responsable area,COUNT(*) total,SUM(CASE WHEN s.estado='PENDIENTE' THEN 1 ELSE 0 END) pendientes,SUM(CASE WHEN s.estado='PENDIENTE' AND s.fecha_limite<datetime('now') THEN 1 ELSE 0 END) vencidas,ROUND(AVG(CASE WHEN s.resuelto_en IS NOT NULL THEN (julianday(s.resuelto_en)-julianday(s.creado_en))*24 END),1) horas FROM solicitudes_aprobacion s{$cond} GROUP BY s.area_responsable ORDER BY pendientes DESC,total DESC")->fetchAll(PDO::FETCH_ASSOC);
$porServicio = $pdo->query("SELECT COALESCE(c.nombre,s.tipo) servicio,COUNT(*) total,SUM(CASE WHEN s.estado='APROBADA' THEN 1 ELSE 0 END) aprobadas,SUM(CASE WHEN s.estado='RECHAZADA' THEN 1 ELSE 0 END) rechazadas FROM solicitudes_aprobacion s LEFT JOIN catalogo_servicios c ON c.id=s.catalogo_id{$cond} GROUP BY COALESCE(c.nombre,s.tipo) ORDER BY total DESC LIMIT 10")->fetchAll(PDO::FETCH_ASSOC);
$eventosSql = "SELECT e.*,s.codigo,c.nombre servicio_nombre FROM solicitudes_aprobacion_eventos e JOIN solicitudes_aprobacion s ON s.id=e.solicitud_id LEFT JOIN catalogo_servicios c ON c.id=s.catalogo_id" . ($area !== null ? ' WHERE s.area_responsable=' . $pdo->quote($area) : '') . ' ORDER BY e.id DESC LIMIT 12';
$eventos = $pdo->query($eventosSql)->fetchAll(PDO::FETCH_ASSOC);
$identidad = $pdo->query("SELECT COUNT(*) total,SUM(CASE WHEN documento IS NOT NULL AND documento!='' THEN 1 ELSE 0 END) vinculados,SUM(CASE WHEN sso_microsoft_id IS NOT NULL AND sso_microsoft_id!='' THEN 1 ELSE 0 END) sso,SUM(CASE WHEN totp_habilitado=1 THEN 1 ELSE 0 END) dos_factores FROM usuarios_sistema WHERE activo=1")->fetch(PDO::FETCH_ASSOC);
$maxArea = max(array_column($porArea, 'total') ?: [1]) ?: 1;
layout_inicio('Gobierno Operativo', 'Gobierno Operativo', '../');
?>
<div class="page-kicker">DIRECCIÓN · CONTROL INTERÁREAS</div><h1>Gobierno Operativo</h1><p class="subtitle">Decisiones, tiempos, exposición económica e identidad digital con datos reales de NAVISSI.<?php if ($area): ?> <span class="badge badge-otro">Área: <?= e($area) ?></span><?php endif; ?></p>
<div class="governance-hero"><div><span class="page-kicker">SOLICITUDES ABIERTAS</span><strong><?= $pendientes ?></strong><p><?= $vencidas ?> fuera de SLA · $<?= number_format($montoPendiente,0,',','.') ?> pendientes de decisión</p></div><a class="btn" href="aprobaciones.php">Abrir bandeja</a></div>
<div class="cards governance-cards"><div class="card <?= $vencidas?'card-err':'card-ok' ?>"><div class="num"><?= $vencidas ?></div><div class="label">SLA vencidos</div></div><div class="card"><div class="num"><?= $tasa ?>%</div><div class="label">Tasa de aprobación · 30 días</div></div><div class="card"><div class="num"><?= number_format($tiempo,1,',','.') ?> h</div><div class="label">Tiempo medio de decisión</div></div><div class="card"><div class="num"><?= (int)$identidad['total'] ?></div><div class="label">Identidades activas</div></div></div>
<div class="panel-grid-2"><section class="panel"><h3>Flujo por área</h3><?php foreach ($porArea as $fila): ?><div class="governance-area"><div><strong><?= e($fila['area'] ?: 'Sin área') ?></strong><small><?= (int)$fila['pendientes'] ?> pendientes · <?= (int)$fila['vencidas'] ?> vencidas</small></div><div class="bar-chart-track"><div class="bar-chart-fill" style="width:<?= max(4,round($fila['total']/$maxArea*100)) ?>%"></div></div><span><?= (int)$fila['total'] ?></span></div><?php endforeach; ?><?php if (!$porArea): ?><p class="small">Aún no hay solicitudes para medir.</p><?php endif; ?></section><section class="panel"><h3>Madurez de identidad</h3><div class="identity-score"><div><strong><?= (int)$identidad['vinculados'] ?>/<?= (int)$identidad['total'] ?></strong><span>Documento vinculado</span></div><div><strong><?= (int)$identidad['sso'] ?>/<?= (int)$identidad['total'] ?></strong><span>Microsoft SSO</span></div><div><strong><?= (int)$identidad['dos_factores'] ?>/<?= (int)$identidad['total'] ?></strong><span>Doble factor</span></div></div><p class="small">Este bloque permite priorizar la integración de identidades sin mezclar cuentas personales con usuarios corporativos.</p></section></div>
<div class="panel-grid-2"><section class="panel"><h3>Servicios más solicitados</h3><table><thead><tr><th>Servicio</th><th>Total</th><th>Aprobadas</th><th>Rechazadas</th></tr></thead><tbody><?php foreach ($porServicio as $s): ?><tr><td><?= e($s['servicio']) ?></td><td><?= (int)$s['total'] ?></td><td><?= (int)$s['aprobadas'] ?></td><td><?= (int)$s['rechazadas'] ?></td></tr><?php endforeach; ?><?php if (!$porServicio): ?><tr><td colspan="4" class="small">Sin datos todavía.</td></tr><?php endif; ?></tbody></table></section><section class="panel"><h3>Decisiones recientes</h3><div class="approval-timeline compact"><?php foreach ($eventos as $evento): ?><a class="timeline-event" href="solicitud_detalle.php?id=<?= (int)$evento['solicitud_id'] ?>"><span class="timeline-dot"></span><div><strong><?= e($evento['codigo']) ?> · <?= e(str_replace('_',' ',$evento['accion'])) ?></strong><p><?= e($evento['actor']) ?> · <?= e($evento['creado_en']) ?></p></div></a><?php endforeach; ?><?php if (!$eventos): ?><p class="small">Sin decisiones registradas.</p><?php endif; ?></div></section></div>
<?php layout_fin(); ?>
