<?php
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../lib/layout.php';
require_once __DIR__ . '/../lib/identidad_lifecycle.php';
requiere_roles(['ADMIN','TI','RRHH','DIRECTOR','GERENCIA','CEO'], '../');
$pdo=db();$actor=usuario_actual();$msg=null;
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['accion']??'')==='crear_ciclo'){
    try{
        $datos=$_POST;$documento=limpio($_POST['empleado_documento']??null);
        if($documento){$s=$pdo->prepare('SELECT * FROM empleados WHERE documento=?');$s->execute([$documento]);if($e=$s->fetch(PDO::FETCH_ASSOC)){$datos['empleado_nombre']=$e['nombres'];$datos['correo_corporativo']=$e['email'];$datos['cargo']=$e['cargo'];$datos['area_origen']=$e['area'];$datos['area_destino']=$datos['area_destino']?:$e['area'];}}
        $ciclo=ciclo_identidad_crear($pdo,$datos,$actor);header('Location: ciclo_identidad_detalle.php?id='.(int)$ciclo['id'].'&creado=1');exit;
    }catch(Throwable $e){$msg=['error',$e->getMessage()];}
}
$diag=identidad_diagnostico($pdo);$filtro=strtoupper((string)($_GET['brecha']??'SIN_NAVISSI'));if(!in_array($filtro,['SIN_NAVISSI','SIN_MICROSOFT','RETIRO_ACTIVO','MICROSOFT_SIN_EMPLEADO'],true))$filtro='SIN_NAVISSI';$brechas=identidad_brechas($pdo,$filtro);$ciclos=$pdo->query('SELECT * FROM ciclos_identidad ORDER BY CASE estado WHEN \'EN_EJECUCION\' THEN 0 WHEN \'APROBADO\' THEN 1 WHEN \'PENDIENTE\' THEN 2 ELSE 3 END,id DESC LIMIT 30')->fetchAll(PDO::FETCH_ASSOC);$empleados=$pdo->query("SELECT documento,nombres,email,area,cargo,estado FROM empleados ORDER BY nombres")->fetchAll(PDO::FETCH_ASSOC);$departamentos=$pdo->query("SELECT nombre FROM departamentos WHERE estado='ACTIVO' ORDER BY nombre")->fetchAll(PDO::FETCH_COLUMN);$solicitudes=$pdo->query("SELECT id,codigo,solicitante_nombre,descripcion FROM solicitudes_aprobacion WHERE estado='APROBADA' AND tipo='USR-ALTA-BAJA' AND id NOT IN(SELECT solicitud_id FROM ciclos_identidad WHERE solicitud_id IS NOT NULL) ORDER BY id DESC")->fetchAll(PDO::FETCH_ASSOC);$solicitudPre=(int)($_GET['solicitud_id']??0);$graphOk=ms365_configurado();
layout_inicio('Gobierno de Identidades','Gobierno de Identidades','../');?>
<div class="page-kicker">FASE 5 · PERSONAS, CUENTAS Y ACTIVOS</div><h1><?=icon('users','icon-lg')?> Gobierno de Identidades</h1><p class="subtitle">Altas, traslados y retiros coordinados entre RRHH, Microsoft 365, NAVISSI e Inventario.</p><?php if($msg):?><div class="msg-<?=e($msg[0])?>"><?=e($msg[1])?></div><?php endif;?>
<div class="identity-hero"><div><span class="page-kicker">MICROSOFT GRAPH</span><strong><?=$graphOk?'CONECTADO':'SIN CONFIGURAR'?></strong><p><?= (int)$pdo->query("SELECT COUNT(*) FROM ms365_usuarios WHERE cuenta_activa=1")->fetchColumn()?> cuentas activas sincronizadas · las bajas requieren confirmación explícita.</p></div><a class="btn btn-secondary" href="microsoft365.php">Microsoft 365</a></div>
<div class="cards identity-gap-cards"><a class="card card-link <?=$diag['sin_usuario_navissi']?'card-warn':'card-ok'?>" href="?brecha=SIN_NAVISSI"><div class="num"><?=$diag['sin_usuario_navissi']?></div><div class="label">Empleados sin usuario NAVISSI</div></a><a class="card card-link <?=$diag['sin_microsoft']?'card-warn':'card-ok'?>" href="?brecha=SIN_MICROSOFT"><div class="num"><?=$diag['sin_microsoft']?></div><div class="label">Empleados sin Microsoft activo</div></a><a class="card card-link <?=$diag['retiros_con_microsoft_activo']?'card-err':'card-ok'?>" href="?brecha=RETIRO_ACTIVO"><div class="num"><?=$diag['retiros_con_microsoft_activo']?></div><div class="label">Retiros con Microsoft activo</div></a><a class="card card-link" href="?brecha=MICROSOFT_SIN_EMPLEADO"><div class="num"><?=$diag['microsoft_sin_empleado']?></div><div class="label">Cuentas Microsoft sin empleado activo</div></a></div>
<div class="panel-grid-2"><section class="panel"><h3>Iniciar ciclo de identidad</h3><form method="post"><input type="hidden" name="accion" value="crear_ciclo"><div class="grid-form"><div><label>Tipo</label><select name="tipo"><option>ALTA</option><option>TRASLADO</option><option>RETIRO</option></select></div><div><label>Empleado registrado</label><select name="empleado_documento"><option value="">Captura manual</option><?php foreach($empleados as $e):?><option value="<?=e($e['documento'])?>"><?=e($e['nombres'])?> · <?=e($e['estado'])?></option><?php endforeach;?></select></div><div><label>Nombre (si es alta nueva)</label><input name="empleado_nombre"></div><div><label>Correo corporativo</label><input type="email" name="correo_corporativo"></div><div><label>Cargo</label><input name="cargo"></div><div><label>Área de destino</label><select name="area_destino"><option value="">Selecciona</option><?php foreach($departamentos as $d):?><option><?=e($d)?></option><?php endforeach;?></select></div><div><label>Fecha efectiva</label><input type="date" name="fecha_efectiva"></div><div><label>Solicitud aprobada</label><select name="solicitud_id"><option value="">Pendiente de aprobación</option><?php foreach($solicitudes as $s):?><option value="<?=(int)$s['id']?>" <?=$solicitudPre===(int)$s['id']?'selected':''?>><?=e($s['codigo'])?> · <?=e($s['solicitante_nombre'])?></option><?php endforeach;?></select></div></div><label>Observaciones</label><textarea name="observaciones" rows="2"></textarea><button style="margin-top:12px">Crear plan de tareas</button></form></section><section class="panel"><h3>Brecha priorizada</h3><div class="toolbar"><a class="btn btn-secondary" href="?brecha=SIN_NAVISSI">NAVISSI</a><a class="btn btn-secondary" href="?brecha=SIN_MICROSOFT">Microsoft</a><a class="btn btn-secondary" href="?brecha=RETIRO_ACTIVO">Retiros</a></div><table><thead><tr><th>Persona / cuenta</th><th>Área</th><th>Acción</th></tr></thead><tbody><?php foreach($brechas as $b):?><tr><td><strong><?=e($b['nombres'])?></strong><br><span class="small"><?=e($b['email'])?></span></td><td><?=e($b['area'])?></td><td><?=e($b['accion'])?></td></tr><?php endforeach;?><?php if(!$brechas):?><tr><td colspan="3" class="small">No hay brechas de este tipo.</td></tr><?php endif;?></tbody></table></section></div>
<section class="panel"><h3>Ciclos recientes</h3><table><thead><tr><th>Código</th><th>Tipo</th><th>Empleado</th><th>Fecha efectiva</th><th>Progreso</th><th>Estado</th></tr></thead><tbody><?php foreach($ciclos as $c):?><tr onclick="location.href='ciclo_identidad_detalle.php?id=<?=(int)$c['id']?>'" style="cursor:pointer"><td><strong><?=e($c['codigo'])?></strong></td><td><?=e($c['tipo'])?></td><td><?=e($c['empleado_nombre'])?><br><span class="small"><?=e($c['correo_corporativo'])?></span></td><td><?=e($c['fecha_efectiva'])?></td><td><div class="cycle-progress"><span style="width:<?=(int)$c['progreso']?>%"></span></div><small><?=(int)$c['progreso']?>%</small></td><td><span class="badge <?=$c['estado']==='COMPLETADO'?'badge-activo':($c['estado']==='PENDIENTE'?'badge-warn':'badge-otro')?>"><?=e($c['estado'])?></span></td></tr><?php endforeach;?><?php if(!$ciclos):?><tr><td colspan="6" class="small">Todavía no hay ciclos creados.</td></tr><?php endif;?></tbody></table></section>
<?php layout_fin();?>
