<?php
require_once __DIR__.'/../config.php';require_once __DIR__.'/../lib/layout.php';require_once __DIR__.'/../lib/inteligencia_operativa.php';
requiere_roles(['ADMIN','TI','GERENCIA','CEO','DIRECTOR'],'../');$pdo=db();$actor=usuario_actual();$msg=null;
if($_SERVER['REQUEST_METHOD']==='POST'){try{$accion=$_POST['accion']??'';if($accion==='ejecutar'){$r=inteligencia_ejecutar($pdo,'MANUAL','manual-intel-'.gmdate('YmdHis').'-'.bin2hex(random_bytes(2)));$msg=['ok',$r['resumen']];}elseif($accion==='crear_ticket'){if(!tiene_rol(['ADMIN','TI']))throw new RuntimeException('Solo TI o Administración puede crear tickets desde hallazgos.');$ticket=inteligencia_crear_ticket($pdo,(int)$_POST['hallazgo_id'],$actor);header('Location: ticket_detalle.php?id='.$ticket);exit;}elseif(in_array($accion,['gestionar','descartar','resolver'],true)){inteligencia_gestionar($pdo,(int)$_POST['hallazgo_id'],$accion,$actor);$msg=['ok','Hallazgo actualizado.'];}}catch(Throwable $e){$msg=['error',$e->getMessage()];}}
$estado=strtoupper((string)($_GET['estado']??'ACTIVO'));if(!in_array($estado,['ACTIVO','GESTIONADO','RESUELTO','DESCARTADO','TODOS'],true))$estado='ACTIVO';$dominio=strtoupper((string)($_GET['dominio']??''));$permitidos=['OPERACION','SERVICIO','IDENTIDAD','ACTIVOS','COSTOS','RETAIL'];if(!in_array($dominio,$permitidos,true))$dominio='';$where=[];$args=[];if($estado!=='TODOS'){$where[]='h.estado=?';$args[]=$estado;}if($dominio){$where[]='h.dominio=?';$args[]=$dominio;}$sql='SELECT h.* FROM inteligencia_hallazgos h'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY CASE h.severidad WHEN \'CRITICA\' THEN 0 WHEN \'ALTA\' THEN 1 WHEN \'MEDIA\' THEN 2 ELSE 3 END,h.actualizado_en DESC LIMIT 100';$s=$pdo->prepare($sql);$s->execute($args);$hallazgos=$s->fetchAll(PDO::FETCH_ASSOC);$metricas=inteligencia_metricas($pdo);$ultima=$pdo->query('SELECT * FROM inteligencia_ejecuciones ORDER BY id DESC LIMIT 1')->fetch(PDO::FETCH_ASSOC);$porAgente=$pdo->query("SELECT agente,COUNT(*) cantidad,SUM(CASE WHEN severidad='CRITICA' THEN 1 ELSE 0 END) criticos FROM inteligencia_hallazgos WHERE estado='ACTIVO' GROUP BY agente ORDER BY cantidad DESC")->fetchAll(PDO::FETCH_ASSOC);
layout_inicio('Inteligencia Operativa','Inteligencia Operativa','../');?>
<div class="page-kicker">FASE 6 · EVIDENCIA ANTES QUE PROMESAS</div><h1><?=icon('dashboard','icon-lg')?> Inteligencia Operativa</h1><p class="subtitle">Agentes de control que leen datos reales de NAVISSI, explican cada hallazgo y dejan la decisión en manos del responsable.</p><?php if($msg):?><div class="msg-<?=e($msg[0])?>"><?=e($msg[1])?></div><?php endif;?>
<section class="intelligence-hero"><div><span>ÚLTIMA LECTURA</span><strong><?=e($ultima['estado']??'SIN EJECUCIONES')?></strong><p><?=e($ultima['resumen']??'Ejecuta la primera lectura transversal.')?></p></div><form method="post"><input type="hidden" name="accion" value="ejecutar"><button><?=icon('zap')?> Leer operación ahora</button></form></section>
<div class="cards intelligence-cards"><a class="card card-link <?=$metricas['criticos']?'card-err':'card-ok'?>" href="?estado=ACTIVO"><div class="num"><?=$metricas['criticos']?></div><div class="label">Críticos activos</div></a><a class="card card-link" href="?estado=ACTIVO"><div class="num"><?=$metricas['activos']?></div><div class="label">Hallazgos activos</div></a><a class="card card-link" href="?estado=GESTIONADO"><div class="num"><?=$metricas['gestionados']?></div><div class="label">En gestión</div></a><a class="card card-link" href="?estado=RESUELTO"><div class="num"><?=$metricas['resueltos_30d']?></div><div class="label">Resueltos · 30 días</div></a></div>
<div class="intelligence-agents"><?php foreach($porAgente as $a):?><article><span><?=e($a['agente'])?></span><strong><?=(int)$a['cantidad']?></strong><small><?=(int)$a['criticos']?> críticos</small></article><?php endforeach;?><?php if(!$porAgente):?><article><span>CONTROL TRANSVERSAL</span><strong>0</strong><small>sin riesgos activos</small></article><?php endif;?></div>
<div class="toolbar intelligence-filters"><a class="btn btn-secondary" href="?estado=ACTIVO">Activos</a><a class="btn btn-secondary" href="?estado=GESTIONADO">En gestión</a><a class="btn btn-secondary" href="?estado=RESUELTO">Resueltos</a><a class="btn btn-secondary" href="?estado=TODOS">Todos</a><?php foreach($permitidos as $d):?><a href="?estado=<?=e($estado)?>&dominio=<?=e($d)?>"><?=e($d)?></a><?php endforeach;?></div>
<section class="intelligence-feed"><?php foreach($hallazgos as $h):$ev=json_decode((string)$h['evidencia_json'],true)?:[];?><article class="intelligence-finding severity-<?=strtolower(e($h['severidad']))?>"><div class="finding-rail"><span><?=e($h['severidad'])?></span><small><?=e($h['dominio'])?></small></div><div class="finding-content"><div class="task-meta"><span><?=e($h['agente'])?></span><span><?=e($h['actualizado_en'])?> UTC</span><span class="badge badge-otro"><?=e($h['estado'])?></span></div><h3><?=e($h['titulo'])?></h3><p><?=e($h['resumen'])?></p><div class="evidence-strip"><?php foreach($ev as $k=>$v):?><span><small><?=e(str_replace('_',' ',$k))?></small><strong><?=e(is_scalar($v)?(string)$v:json_encode($v))?></strong></span><?php endforeach;?></div></div><div class="finding-actions"><?php if($h['accion_url']):?><a class="btn btn-secondary" href="<?=e($h['accion_url'])?>">Ver origen</a><?php endif;?><?php if($h['ticket_id']):?><a class="btn" href="ticket_detalle.php?id=<?=(int)$h['ticket_id']?>">Ticket #<?=(int)$h['ticket_id']?></a><?php elseif(in_array($h['estado'],['ACTIVO','GESTIONADO'],true)&&tiene_rol(['ADMIN','TI'])):?><form method="post"><input type="hidden" name="accion" value="crear_ticket"><input type="hidden" name="hallazgo_id" value="<?=(int)$h['id']?>"><button>Crear ticket</button></form><?php endif;?><?php if($h['estado']==='ACTIVO'):?><form method="post"><input type="hidden" name="accion" value="gestionar"><input type="hidden" name="hallazgo_id" value="<?=(int)$h['id']?>"><button class="btn-secondary">Tomar gestión</button></form><form method="post"><input type="hidden" name="accion" value="descartar"><input type="hidden" name="hallazgo_id" value="<?=(int)$h['id']?>"><button class="btn-secondary">Descartar</button></form><?php elseif($h['estado']==='GESTIONADO'):?><form method="post"><input type="hidden" name="accion" value="resolver"><input type="hidden" name="hallazgo_id" value="<?=(int)$h['id']?>"><button>Resolver</button></form><?php endif;?></div></article><?php endforeach;?><?php if(!$hallazgos):?><div class="panel empty-intelligence"><strong>Sin hallazgos en esta vista</strong><p>La ausencia de alertas también queda respaldada por la última ejecución.</p></div><?php endif;?></section>
<?php layout_fin();?>
