<?php
require_once __DIR__.'/../config.php';require_once __DIR__.'/../lib/layout.php';require_once __DIR__.'/../lib/salud_tiendas.php';
requiere_roles(['ADMIN','TI','GERENCIA','CEO','COORDINADOR','DIRECTOR'],'../');$pdo=db();$msg=null;
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['accion']??'')==='registrar'){$sid=(int)($_POST['sede_id']??0);$mom=strtoupper((string)($_POST['momento']??'VALIDACION'));$estado=strtoupper((string)($_POST['estado']??'OK'));$obs=limpio($_POST['observaciones']??null);if(!in_array($mom,['APERTURA','CIERRE','VALIDACION'],true))$mom='VALIDACION';if(!in_array($estado,['OK','ALERTA','BLOQUEO'],true))$estado='OK';$ss=$pdo->prepare("SELECT id,nombre FROM sedes WHERE id=? AND estado='ACTIVO'");$ss->execute([$sid]);$site=$ss->fetch(PDO::FETCH_ASSOC);
 if(!$site)$msg=['error','Selecciona una tienda activa.'];elseif($estado!=='OK'&&!$obs)$msg=['error','Describe la novedad.'];else{$pdo->beginTransaction();try{$ticket=null;if(!empty($_POST['crear_ticket'])&&$estado!=='OK'){$pri=$estado==='BLOQUEO'?'URGENTE':'ALTA';$sla=gmdate('Y-m-d H:i:s',strtotime($estado==='BLOQUEO'?'+4 hours':'+8 hours'));$u=usuario_actual();$pdo->prepare("INSERT INTO tickets(titulo,descripcion,categoria,prioridad,sede_id,solicitante,solicitante_contacto,sla_limite,origen,solicitante_area)VALUES(?,?,?,?,?,?,?,?,?,?)")->execute(["{$mom} {$estado} — {$site['nombre']}",$obs,'INFRAESTRUCTURA',$pri,$sid,$u['nombre']??'Operación',$u['email']??null,$sla,'SALUD_TIENDA','TI']);$ticket=(int)$pdo->lastInsertId();}$u=usuario_actual();$pdo->prepare("INSERT INTO salud_tiendas_registros(sede_id,momento,estado,internet_ok,pos_ok,impresora_ok,datafono_ok,observaciones,responsable,ticket_id)VALUES(?,?,?,?,?,?,?,?,?,?)")->execute([$sid,$mom,$estado,!empty($_POST['internet_ok']),!empty($_POST['pos_ok']),!empty($_POST['impresora_ok']),!empty($_POST['datafono_ok']),$obs,$u['nombre']??'Sistema',$ticket]);$pdo->commit();$msg=['ok',$ticket?"Validación guardada y ticket #{$ticket} creado.":'Validación guardada.'];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$msg=['error','No fue posible guardar.'];}}
}
$q=trim((string)($_GET['q']??''));$zona=trim((string)($_GET['zona']??''));$nivel=trim((string)($_GET['nivel']??''));$rows=salud_tiendas_resumen($pdo,$q?:null,$zona?:null);if($nivel)$rows=array_values(array_filter($rows,fn($r)=>$r['nivel']===$nivel));$sedes=$pdo->query("SELECT id,nombre FROM sedes WHERE estado='ACTIVO' ORDER BY nombre")->fetchAll(PDO::FETCH_ASSOC);$zonas=$pdo->query("SELECT DISTINCT zona FROM sedes WHERE zona IS NOT NULL AND zona!='' ORDER BY zona")->fetchAll(PDO::FETCH_COLUMN);$tot=['ESTABLE'=>0,'ATENCION'=>0,'CRITICO'=>0];foreach($rows as $r)$tot[$r['nivel']]++;$hoy=count(array_filter($rows,fn($r)=>(int)$r['validada_hoy']));
layout_inicio('Salud de Tiendas','Salud de Tiendas','../');?>
<div class="page-kicker">OPERACIÓN RETAIL · TIENDAS</div><h1><?=icon('store','icon-lg')?> Salud de Tiendas</h1><p class="subtitle">Apertura, conectividad, equipos y tickets por punto de venta.</p><?php if($msg):?><div class="msg-<?=e($msg[0])?>"><?=e($msg[1])?></div><?php endif;?>
<div class="cards"><div class="card card-ok"><div class="num"><?=$tot['ESTABLE']?></div><div class="label">Estables</div></div><div class="card card-warn"><div class="num"><?=$tot['ATENCION']?></div><div class="label">Requieren atención</div></div><div class="card card-err"><div class="num"><?=$tot['CRITICO']?></div><div class="label">Críticas</div></div><div class="card"><div class="num"><?=$hoy?>/<?=count($rows)?></div><div class="label">Validadas hoy</div></div></div>
<div class="panel"><h3><?=icon('check')?> Registrar validación</h3><form method="post"><input type="hidden" name="accion" value="registrar"><div class="grid-form"><div><label>Tienda</label><select name="sede_id" required><option value="">Seleccionar</option><?php foreach($sedes as $s):?><option value="<?=$s['id']?>"><?=e($s['nombre'])?></option><?php endforeach;?></select></div><div><label>Momento</label><select name="momento"><option>APERTURA</option><option>VALIDACION</option><option>CIERRE</option></select></div><div><label>Resultado</label><select name="estado" id="salud-estado"><option value="OK">Sin novedad</option><option value="ALERTA">Alerta</option><option value="BLOQUEO">Bloqueo operativo</option></select></div></div><div class="check-grid"><?php foreach(['internet'=>'Internet','pos'=>'POS / Siesa','impresora'=>'Impresora','datafono'=>'Datáfono'] as $k=>$v):?><label><input type="checkbox" name="<?=$k?>_ok" checked> <?=$v?></label><?php endforeach;?></div><textarea name="observaciones" rows="3" style="width:100%" placeholder="Describe la novedad y su impacto."></textarea><label class="ticket-switch"><input type="checkbox" name="crear_ticket" id="crear-ticket"> Crear ticket para TI si hay novedad</label><button><?=icon('check')?> Guardar validación</button></form></div>
<form class="toolbar" method="get"><input name="q" value="<?=e($q)?>" placeholder="Buscar tienda, ciudad o zona"><select name="zona"><option value="">Todas las zonas</option><?php foreach($zonas as $z):?><option <?=$zona===$z?'selected':''?>><?=e($z)?></option><?php endforeach;?></select><select name="nivel"><option value="">Todos los estados</option><?php foreach(['ESTABLE','ATENCION','CRITICO'] as $n):?><option <?=$nivel===$n?'selected':''?>><?=$n?></option><?php endforeach;?></select><button>Filtrar</button></form>
<div class="tabla-scroll"><table class="tabla-tickets"><thead><tr><th>Tienda</th><th>Pulso</th><th>Validación</th><th>Equipos / agentes</th><th>Tickets</th><th>Novedad</th></tr></thead><tbody><?php foreach($rows as $r):$cls=$r['nivel']==='ESTABLE'?'badge-activo':($r['nivel']==='CRITICO'?'badge-err':'badge-warn');?><tr><td><strong><?=e($r['nombre'])?></strong><br><span class="small"><?=e($r['ciudad'])?> · <?=e($r['zona'])?></span></td><td><span class="salud-score"><?=$r['puntaje']?></span> <span class="badge <?=$cls?>"><?=$r['nivel']?></span></td><td><span class="badge <?=$r['validada_hoy']?'badge-activo':'badge-warn'?>"><?=$r['validada_hoy']?'HOY':'PENDIENTE'?></span></td><td><?=$r['equipos']?> equipos<br><span class="small"><?=$r['agentes_recientes']?>/<?=$r['agentes_instalados']?> agentes</span></td><td><?=$r['tickets_abiertos']?> abiertos<br><?php if($r['sla_vencidos']):?><span class="badge badge-err"><?=$r['sla_vencidos']?> SLA</span><?php endif;?></td><td><?=e($r['ultima_observacion']?:'Sin novedades')?></td></tr><?php endforeach;?></tbody></table></div>
<script>document.getElementById('salud-estado').addEventListener('change',function(){document.getElementById('crear-ticket').checked=this.value!=='OK'});</script><?php layout_fin();?>
