<?php
declare(strict_types=1);require_once __DIR__.'/../config.php';require_once __DIR__.'/../lib/retail_analytics.php';require_once __DIR__.'/../lib/inteligencia_operativa.php';
function fase7_ok(bool $c,string $m):void{if(!$c)throw new RuntimeException("FAIL {$m}");echo "OK  {$m}\n";}$pdo=db();$actor=['nombre'=>'QA Retail'];
$productos=[['sku'=>'REF-A-S','referencia'=>'REF-A','descripcion'=>'Vestido A','categoria'=>'VESTIDOS','color'=>'NEGRO','talla'=>'S'],['sku'=>'REF-A-M','referencia'=>'REF-A','descripcion'=>'Vestido A','categoria'=>'VESTIDOS','color'=>'NEGRO','talla'=>'M'],['sku'=>'REF-A-L','referencia'=>'REF-A','descripcion'=>'Vestido A','categoria'=>'VESTIDOS','color'=>'NEGRO','talla'=>'L'],['sku'=>'REF-B-U','referencia'=>'REF-B','descripcion'=>'Blusa B','categoria'=>'BLUSAS','talla'=>'U'],['sku'=>'REF-C-U','referencia'=>'REF-C','descripcion'=>'Jean C','categoria'=>'JEANS','talla'=>'U']];
$existencias=[['fecha'=>'2026-07-13','sku'=>'REF-A-S','sede_codigo'=>'001','sede_nombre'=>'Tienda QA','unidades'=>0],['fecha'=>'2026-07-13','sku'=>'REF-A-M','sede_codigo'=>'001','sede_nombre'=>'Tienda QA','unidades'=>2],['fecha'=>'2026-07-13','sku'=>'REF-A-L','sede_codigo'=>'001','sede_nombre'=>'Tienda QA','unidades'=>0],['fecha'=>'2026-07-13','sku'=>'REF-B-U','sede_codigo'=>'001','sede_nombre'=>'Tienda QA','unidades'=>100],['fecha'=>'2026-07-13','sku'=>'REF-C-U','sede_codigo'=>'001','sede_nombre'=>'Tienda QA','unidades'=>100]];
$ventas=[['fecha'=>'2026-07-13','documento'=>'FV-1','linea_documento'=>'1','sku'=>'REF-A-S','sede_codigo'=>'001','unidades'=>10,'valor_neto'=>1000000],['fecha'=>'2026-07-13','documento'=>'FV-1','linea_documento'=>'2','sku'=>'REF-A-M','sede_codigo'=>'001','unidades'=>28,'valor_neto'=>2800000],['fecha'=>'2026-07-13','documento'=>'FV-1','linea_documento'=>'3','sku'=>'REF-C-U','sede_codigo'=>'001','unidades'=>28,'valor_neto'=>2800000],['fecha'=>'2026-07-13','documento'=>'FV-1','linea_documento'=>'4','sede_codigo'=>'001','unidades'=>1,'valor_neto'=>100000]];
$r=retail_importar_lote($pdo,'siesa-qa-001',['productos'=>$productos,'existencias'=>$existencias,'ventas'=>$ventas],$actor);fase7_ok(!$r['duplicada']&&$r['importadas']===13&&$r['errores']===1,'importa productos, existencias y ventas con control de calidad');fase7_ok(retail_importar_lote($pdo,'siesa-qa-001',[], $actor)['duplicada'],'evita duplicar el mismo lote Siesa');
$csv=tempnam(sys_get_temp_dir(),'navissi-retail-');file_put_contents($csv,"SKU;REFERENCIA;DESCRIPCION;TALLA\nREF-D-S;REF-D;Camisa D;S\n");$csvImport=retail_importar_archivo($pdo,$csv,'productos.csv','PRODUCTOS',$actor);fase7_ok(!$csvImport['duplicada']&&$csvImport['importadas']===1,'procesa plantilla CSV con separador de Siesa');fase7_ok(retail_importar_archivo($pdo,$csv,'productos.csv','PRODUCTOS',$actor)['duplicada'],'evita reprocesar el mismo archivo');@unlink($csv);
$a=retail_analitica($pdo);$estados=array_column($a['filas'],'estado','sku');fase7_ok($a['corte']==='2026-07-13'&&$estados['REF-A-S']==='QUIEBRE'&&$estados['REF-A-M']==='RIESGO','calcula quiebre y riesgo por cobertura');fase7_ok($estados['REF-A-L']==='HUECO_TALLA'&&(int)$a['metricas']['huecos_talla']===1,'detecta huecos dentro de la curva de tallas');fase7_ok($estados['REF-B-U']==='SIN_ROTACION'&&$estados['REF-C-U']==='SOBRESTOCK','distingue sin rotación y sobrestock');fase7_ok((int)$a['metricas']['ventas_28d']===66&&(int)$a['metricas']['valor_28d']===6600000,'reconcilia unidades y venta neta de 28 días');
$intel=inteligencia_ejecutar($pdo,'TEST','fase7-intel',new DateTimeImmutable('2026-07-13 20:00:00',new DateTimeZone('UTC')));fase7_ok((int)$pdo->query("SELECT COUNT(*) FROM inteligencia_hallazgos WHERE clave_unica IN('INT-RETAIL-COBERTURA','INT-RETAIL-SOBRESTOCK') AND estado='ACTIVO'")->fetchColumn()===2,'publica riesgos retail en Inteligencia Operativa');
echo "PASS phase7_retail_test\n";
