<?php
declare(strict_types=1);require_once __DIR__.'/../config.php';require_once __DIR__.'/../lib/siesa_connector.php';function fase8_ok(bool $c,string $m):void{if(!$c)throw new RuntimeException("FAIL {$m}");echo "OK  {$m}\n";}$pdo=db();
$cfg=siesa_integracion_guardar(['modo'=>'API_REST','auth_type'=>'OAUTH2_CLIENT_CREDENTIALS','base_url'=>'https://api.pruebas.siesa.example','token_url'=>'https://auth.pruebas.siesa.example/token','client_id'=>'navissi-qa','client_secret'=>'secreto-qa','scope'=>'retail.read','productos_path'=>'/items','existencias_path'=>'/inventory','ventas_path'=>'/sales','intervalo_minutos'=>60]);
fase8_ok(!$cfg['habilitado']&&!$cfg['confirmado_oficial'],'mantiene la conexión detenida hasta autorización formal');fase8_ok(secreto_cifrado(trim((string)file_get_contents(siesa_integracion_path()))),'cifra credenciales Siesa en reposo');
$cfg=siesa_integracion_guardar(array_replace($cfg,['client_secret'=>'','scope'=>'retail.read']));fase8_ok($cfg['client_secret']==='secreto-qa','conserva el secreto cuando el formulario llega vacío');
$rechazo=false;try{siesa_integracion_guardar(array_replace($cfg,['habilitado'=>1,'confirmado_oficial'=>0]));}catch(RuntimeException $e){$rechazo=str_contains($e->getMessage(),'autorizó');}fase8_ok($rechazo,'impide activar una integración no autorizada');
$http=false;try{siesa_integracion_guardar(array_replace($cfg,['base_url'=>'http://api.siesa.example']));}catch(InvalidArgumentException $e){$http=str_contains($e->getMessage(),'HTTPS');}fase8_ok($http,'rechaza endpoints sin HTTPS');
$prueba=false;try{siesa_probar_conexion($pdo,['nombre'=>'QA']);}catch(RuntimeException $e){$prueba=str_contains($e->getMessage(),'autorizada');}fase8_ok($prueba&&(int)$pdo->query("SELECT COUNT(*) FROM siesa_integracion_log WHERE accion='PRUEBA' AND estado='ERROR'")->fetchColumn()===1,'audita y bloquea pruebas antes de la autorización');
fase8_ok(siesa_sincronizar_programada($pdo)===null,'la tarea programada no conecta mientras esté deshabilitada');fase8_ok(count(siesa_integracion_lista(['data'=>[['sku'=>'1']]]))===1,'reconoce un sobre de respuesta API sin inventar campos');
echo "PASS phase8_siesa_connector_test\n";
