<?php
require_once __DIR__.'/notificaciones.php';
require_once __DIR__.'/inteligencia_operativa.php';
function automatizacion_config(PDO $p,string $k,int $d): int{$s=$p->prepare("SELECT valor FROM config_general WHERE clave=?");$s->execute([$k]);$v=$s->fetchColumn();return $v!==false?max(0,(int)$v):$d;}
function automatizacion_alerta(PDO $p,string $k,string $t,string $cat,string $g,string $tipo,string $eid,?int $ticket=null):void{$p->prepare("INSERT INTO alertas_sistema(clave_unica,titulo,categoria,gravedad,entidad_tipo,entidad_id,ticket_id,estado) VALUES(?,?,?,?,?,?,?,'ACTIVA') ON CONFLICT(clave_unica) DO UPDATE SET titulo=excluded.titulo,gravedad=excluded.gravedad,ticket_id=excluded.ticket_id,estado='ACTIVA',resuelto_en=NULL")->execute([$k,$t,$cat,$g,$tipo,$eid,$ticket]);}
function automatizacion_operativa_ejecutar(PDO $p,string $trigger='MANUAL',?string $corr=null,?DateTimeImmutable $now=null):array{
 $lockDir=private_path('locks');if(!is_dir($lockDir))@mkdir($lockDir,0700,true);$lock=@fopen($lockDir.DIRECTORY_SEPARATOR.'automatizacion-operativa.lock','c+');
 if(!$lock||!flock($lock,LOCK_EX|LOCK_NB)){if($lock)fclose($lock);return ['ok'=>true,'duplicada'=>false,'ocupada'=>true,'ejecucion_id'=>null,'resumen'=>'Otro ciclo ya está en ejecución.','detalles'=>[]];}
 try{
 $now=($now?:new DateTimeImmutable('now',new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('UTC'));$corr=preg_replace('/[^A-Za-z0-9_.:\-]/','',(string)($corr?:strtolower($trigger).'-'.$now->format('YmdHi')));
 $s=$p->prepare("SELECT * FROM automatizacion_ejecuciones WHERE correlacion=?");$s->execute([$corr]);if($x=$s->fetch(PDO::FETCH_ASSOC))return ['ok'=>$x['estado']==='COMPLETADA','duplicada'=>true,'ejecucion_id'=>(int)$x['id'],'resumen'=>$x['resumen'],'detalles'=>json_decode((string)$x['detalles_json'],true)?:[]];
 $p->prepare("INSERT INTO automatizacion_ejecuciones(correlacion,disparador)VALUES(?,?)")->execute([$corr,strtoupper($trigger)]);$rid=(int)$p->lastInsertId();$d=['aperturas_pendientes'=>0,'cierres_pendientes'=>0,'sla_nivel_1'=>0,'sla_nivel_2'=>0,'alertas_resueltas'=>0,'notificaciones_creadas'=>0,'notificaciones_enviadas'=>0,'hallazgos_inteligencia'=>0];
 try{$tz=new DateTimeZone('America/Bogota');$local=$now->setTimezone($tz);$ini=$local->setTime(0,0)->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');$fin=$local->setTime(23,59,59)->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');$gr=automatizacion_config($p,'AUTOMATIZACION_GRACIA_MINUTOS',20);$n2=automatizacion_config($p,'AUTOMATIZACION_SLA_NIVEL2_HORAS',4);
  $old=$p->prepare("UPDATE alertas_sistema SET estado='RESUELTA',resuelto_en=CURRENT_TIMESTAMP WHERE estado='ACTIVA' AND (clave_unica LIKE 'APERTURA_PENDIENTE_%' OR clave_unica LIKE 'CIERRE_PENDIENTE_%') AND clave_unica NOT LIKE ?");$old->execute(['%_'.$local->format('Ymd')]);$d['alertas_resueltas']+=$old->rowCount();
  $hs=$p->prepare("SELECT s.id,s.nombre,s.correo_corporativo,h.hora_apertura,h.hora_cierre,h.cerrado FROM sedes s JOIN horarios_sede h ON h.sede_id=s.id WHERE s.estado='ACTIVO' AND h.dia_semana=?");$hs->execute([(int)$local->format('w')]);$chk=$p->prepare("SELECT COUNT(*) FROM salud_tiendas_registros WHERE sede_id=? AND momento=? AND creado_en BETWEEN ? AND ?");
  foreach($hs->fetchAll(PDO::FETCH_ASSOC) as $site){if($site['cerrado'])continue;foreach(['APERTURA'=>$site['hora_apertura'],'CIERRE'=>$site['hora_cierre']] as $mom=>$hora){if(!$hora)continue;$lim=(new DateTimeImmutable($local->format('Y-m-d').' '.$hora,$tz))->modify("+{$gr} minutes")->setTimezone(new DateTimeZone('UTC'));$key="{$mom}_PENDIENTE_{$site['id']}_{$local->format('Ymd')}";$chk->execute([$site['id'],$mom,$ini,$fin]);if((int)$chk->fetchColumn()){ $p->prepare("UPDATE alertas_sistema SET estado='RESUELTA',resuelto_en=CURRENT_TIMESTAMP WHERE clave_unica=? AND estado='ACTIVA'")->execute([$key]);continue;}if($now>=$lim){$f=$mom==='APERTURA'?'aperturas_pendientes':'cierres_pendientes';$d[$f]++;$title="{$site['nombre']} no registró {$mom} dentro del horario";automatizacion_alerta($p,$key,$title,'Operación retail',$mom==='APERTURA'?'CRITICO':'ADVERTENCIA','SEDE',(string)$site['id']);$extra=filter_var($site['correo_corporativo'],FILTER_VALIDATE_EMAIL)?[$site['correo_corporativo']]:[];$d['notificaciones_creadas']+=notificaciones_encolar_operacion($p,$key,$title,"Validación pendiente después de {$gr} minutos de gracia.",$extra,['sede_id'=>(int)$site['id']]);}}}
  $ts=$p->prepare("SELECT t.*,c.tecnico_default,(julianday(?) - julianday(t.sla_limite))*24 horas_vencido FROM tickets t LEFT JOIN categorias_tickets c ON c.nombre=t.categoria WHERE t.estado NOT IN('CERRADO','RESUELTO POR IA') AND t.sla_limite IS NOT NULL AND t.sla_limite<?");$sqlnow=$now->format('Y-m-d H:i:s');$ts->execute([$sqlnow,$sqlnow]);
  foreach($ts->fetchAll(PDO::FETCH_ASSOC) as $t){$id=(int)$t['id'];if(empty($t['asignado_a'])&&!empty($t['tecnico_default'])){$p->prepare("UPDATE tickets SET asignado_a=? WHERE id=?")->execute([$t['tecnico_default'],$id]);$t['asignado_a']=$t['tecnico_default'];}$levels=[1];if((float)$t['horas_vencido']>=$n2)$levels[]=2;foreach($levels as $lv){$dest=$lv===1?($t['asignado_a']?:'Mesa de Ayuda TI'):'Coordinación / Dirección TI';$mot=$lv===1?'SLA vencido: requiere atención inmediata.':"SLA vencido hace {$n2}+ horas: requiere escalamiento de gestión.";$e=$p->prepare("INSERT OR IGNORE INTO tickets_escalamientos(ticket_id,nivel,motivo,destinatario)VALUES(?,?,?,?)");$e->execute([$id,$lv,$mot,$dest]);if($e->rowCount()){$d[$lv===1?'sla_nivel_1':'sla_nivel_2']++;$p->prepare("INSERT INTO tickets_comentarios(ticket_id,autor,comentario,tipo)VALUES(?,?,?,'SISTEMA')")->execute([$id,'Automatización NAVISSI',"Escalamiento SLA nivel {$lv}: {$mot} Destinatario: {$dest}"]);$emails=[];if((int)automatizacion_config($p,'AUTOMATIZACION_EMAIL_SLA',0)===1){if($lv===1&&$t['asignado_a']){$q=$p->prepare("SELECT email FROM usuarios_sistema WHERE nombre=? AND activo=1 LIMIT 1");$q->execute([$t['asignado_a']]);if($m=$q->fetchColumn())$emails[]=$m;}if($lv===2)$emails=array_merge($emails,$p->query("SELECT email FROM usuarios_sistema WHERE activo=1 AND email IS NOT NULL AND rol IN('SUPER_ADMIN','ADMIN','DIRECTOR')")->fetchAll(PDO::FETCH_COLUMN));$d['notificaciones_creadas']+=notificaciones_encolar_operacion($p,"SLA_ESCALADO_{$id}_{$lv}","Ticket #{$id} · SLA nivel {$lv}",$t['titulo']."\n".$mot,$emails,['ticket_id'=>$id]);}}}automatizacion_alerta($p,"SLA_ESCALADO_{$id}_{$lv}","Ticket #{$id} · {$t['titulo']} · SLA nivel {$lv}",'Mesa de Ayuda',$lv===2?'CRITICO':'ADVERTENCIA','TICKET',(string)$id,$id);}}
  $rr=$p->exec("UPDATE alertas_sistema SET estado='RESUELTA',resuelto_en=CURRENT_TIMESTAMP WHERE clave_unica LIKE 'SLA_ESCALADO_%' AND estado='ACTIVA' AND ticket_id IN(SELECT id FROM tickets WHERE estado IN('CERRADO','RESUELTO POR IA'))");$d['alertas_resueltas']+=(int)$rr;$env=notificaciones_procesar($p,20);$d['notificaciones_enviadas']=$env['enviadas'];try{$intel=inteligencia_ejecutar($p,'AUTOMATIZACION',$corr.'-intel',$now);$d['hallazgos_inteligencia']=(int)($intel['hallazgos']??0);}catch(Throwable $intelError){$d['inteligencia_error']=true;}$sum="{$d['aperturas_pendientes']} aperturas, {$d['cierres_pendientes']} cierres, ".($d['sla_nivel_1']+$d['sla_nivel_2'])." escalaciones y {$d['hallazgos_inteligencia']} hallazgos";$p->prepare("UPDATE automatizacion_ejecuciones SET estado='COMPLETADA',resumen=?,detalles_json=?,finalizado_en=CURRENT_TIMESTAMP WHERE id=?")->execute([$sum,json_encode($d,JSON_UNESCAPED_UNICODE),$rid]);return ['ok'=>true,'duplicada'=>false,'ejecucion_id'=>$rid,'resumen'=>$sum,'detalles'=>$d];
 }catch(Throwable $e){$p->prepare("UPDATE automatizacion_ejecuciones SET estado='ERROR',resumen='Error interno',finalizado_en=CURRENT_TIMESTAMP WHERE id=?")->execute([$rid]);throw $e;}
 }finally{flock($lock,LOCK_UN);fclose($lock);}
}
