<?php
require_once __DIR__.'/xlsx_reader.php';

function retail_normalizar_cabecera(string $valor):string{
    $valor=mb_strtoupper(trim($valor),'UTF-8');$valor=strtr($valor,['Á'=>'A','É'=>'E','Í'=>'I','Ó'=>'O','Ú'=>'U','Ü'=>'U','Ñ'=>'N']);
    return trim(preg_replace('/[^A-Z0-9]+/','_',$valor),'_');
}
function retail_filas_asociativas(array $filas):array{
    if(!$filas)return [];$cab=array_map(fn($v)=>retail_normalizar_cabecera((string)$v),array_shift($filas));$salida=[];
    foreach($filas as $fila){$x=[];foreach($cab as $i=>$k)if($k!=='')$x[$k]=$fila[$i]??null;if(array_filter($x,fn($v)=>$v!==null&&trim((string)$v)!==''))$salida[]=$x;}return $salida;
}
function retail_valor(array $fila,array $alias,$default=null){foreach($alias as $a){$k=retail_normalizar_cabecera($a);if(array_key_exists($k,$fila)&&trim((string)$fila[$k])!=='')return $fila[$k];}return $default;}
function retail_numero($valor):float{
    if(is_int($valor)||is_float($valor))return (float)$valor;$v=preg_replace('/[^0-9,\.\-]/','',(string)$valor);if($v===''||$v==='-')return 0.0;
    if(str_contains($v,',')&&str_contains($v,'.')){$v=strrpos($v,',')>strrpos($v,'.')?str_replace(',','.',str_replace('.','',$v)):str_replace(',','',$v);}elseif(str_contains($v,','))$v=str_replace(',','.',$v);return is_numeric($v)?(float)$v:0.0;
}
function retail_fecha($valor):?string{
    if(is_numeric($valor)&&(float)$valor>20000){$base=new DateTimeImmutable('1899-12-30',new DateTimeZone('UTC'));return $base->modify('+'.(int)$valor.' days')->format('Y-m-d');}
    $v=trim((string)$valor);if($v==='')return null;foreach(['Y-m-d','Y/m/d','d/m/Y','d-m-Y','m/d/Y'] as $f){$d=DateTimeImmutable::createFromFormat('!'.$f,$v,new DateTimeZone('UTC'));if($d&&$d->format($f)===$v)return $d->format('Y-m-d');}try{return (new DateTimeImmutable($v))->format('Y-m-d');}catch(Throwable $e){return null;}
}
function retail_upsert_producto(PDO $pdo,string $sku,array $fila):void{
    $referencia=trim((string)retail_valor($fila,['REFERENCIA','REF'],''));$descripcion=trim((string)retail_valor($fila,['DESCRIPCION','PRODUCTO','NOMBRE'],''));
    $pdo->prepare("INSERT INTO retail_productos(sku,referencia,descripcion,categoria,color,talla,costo,precio)VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(sku) DO UPDATE SET referencia=COALESCE(NULLIF(excluded.referencia,''),retail_productos.referencia),descripcion=COALESCE(NULLIF(excluded.descripcion,''),retail_productos.descripcion),categoria=COALESCE(NULLIF(excluded.categoria,''),retail_productos.categoria),color=COALESCE(NULLIF(excluded.color,''),retail_productos.color),talla=COALESCE(NULLIF(excluded.talla,''),retail_productos.talla),costo=COALESCE(excluded.costo,retail_productos.costo),precio=COALESCE(excluded.precio,retail_productos.precio),actualizado_en=CURRENT_TIMESTAMP")
        ->execute([$sku,$referencia?:null,$descripcion?:null,retail_valor($fila,['CATEGORIA','LINEA','GRUPO']),retail_valor($fila,['COLOR']),retail_valor($fila,['TALLA']),retail_valor($fila,['COSTO'])!==null?retail_numero(retail_valor($fila,['COSTO'])):null,retail_valor($fila,['PRECIO','PRECIO_VENTA'])!==null?retail_numero(retail_valor($fila,['PRECIO','PRECIO_VENTA'])):null]);
}
function retail_error(PDO $pdo,int $importacion,string $dataset,string $hoja,int $fila,string $motivo,array $datos):void{$pdo->prepare('INSERT INTO retail_importacion_errores(importacion_id,dataset,hoja,fila,motivo,datos_json)VALUES(?,?,?,?,?,?)')->execute([$importacion,$dataset,$hoja,$fila,$motivo,json_encode($datos,JSON_UNESCAPED_UNICODE)]);}

function retail_importar_dataset(PDO $pdo,string $tipo,array $filas,int $importacionId,string $hoja,string $fuente,array &$stats):void{
    $tipo=strtoupper($tipo);foreach($filas as $i=>$fila){$stats['leidas']++;$n=$i+2;try{
        $sku=trim((string)retail_valor($fila,['SKU','CODIGO','CODIGO_ITEM','ITEM','REFERENCIA_TALLA']));if($sku==='')throw new InvalidArgumentException('Falta SKU o código de ítem.');
        retail_upsert_producto($pdo,$sku,$fila);
        if($tipo==='PRODUCTOS'){$stats['importadas']++;continue;}
        $fecha=retail_fecha(retail_valor($fila,['FECHA','FECHA_MOVIMIENTO','FECHA_DOCUMENTO','FECHA_CORTE']));if(!$fecha)throw new InvalidArgumentException('Fecha inválida o vacía.');
        $sedeCodigo=trim((string)retail_valor($fila,['SEDE_CODIGO','BODEGA','CENTRO_OPERACION','CO','TIENDA_CODIGO','SEDE']));$sedeNombre=trim((string)retail_valor($fila,['SEDE_NOMBRE','TIENDA','BODEGA_NOMBRE','NOMBRE_SEDE'],$sedeCodigo));if($sedeCodigo==='')throw new InvalidArgumentException('Falta código de sede, bodega o centro de operación.');
        if($tipo==='EXISTENCIAS'){$unidades=retail_numero(retail_valor($fila,['UNIDADES','EXISTENCIA','STOCK','CANTIDAD'],0));$pdo->prepare("INSERT INTO retail_existencias(fecha,sku,sede_codigo,sede_nombre,unidades,costo_unitario,importacion_id,fuente)VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(fecha,sku,sede_codigo) DO UPDATE SET sede_nombre=excluded.sede_nombre,unidades=excluded.unidades,costo_unitario=excluded.costo_unitario,importacion_id=excluded.importacion_id,fuente=excluded.fuente")->execute([$fecha,$sku,$sedeCodigo,$sedeNombre?:$sedeCodigo,$unidades,retail_valor($fila,['COSTO_UNITARIO','COSTO'])!==null?retail_numero(retail_valor($fila,['COSTO_UNITARIO','COSTO'])):null,$importacionId,$fuente]);}
        elseif($tipo==='VENTAS'){$doc=trim((string)retail_valor($fila,['DOCUMENTO','FACTURA','NUMERO_DOCUMENTO','ID_VENTA']));if($doc==='')throw new InvalidArgumentException('Falta documento o factura.');$linea=trim((string)retail_valor($fila,['LINEA_DOCUMENTO','LINEA','RENGLON'],(string)($i+1)));$unidades=retail_numero(retail_valor($fila,['UNIDADES','CANTIDAD'],0));if($unidades==0)throw new InvalidArgumentException('Las unidades no pueden ser cero.');$pdo->prepare("INSERT INTO retail_ventas(fecha,documento,linea,sku,sede_codigo,sede_nombre,unidades,valor_neto,costo,canal,importacion_id,fuente)VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(documento,linea,sku,sede_codigo) DO UPDATE SET fecha=excluded.fecha,sede_nombre=excluded.sede_nombre,unidades=excluded.unidades,valor_neto=excluded.valor_neto,costo=excluded.costo,canal=excluded.canal,importacion_id=excluded.importacion_id,fuente=excluded.fuente")->execute([$fecha,$doc,$linea,$sku,$sedeCodigo,$sedeNombre?:$sedeCodigo,$unidades,retail_numero(retail_valor($fila,['VALOR_NETO','VENTA_NETA','TOTAL','VALOR'],0)),retail_valor($fila,['COSTO','COSTO_TOTAL'])!==null?retail_numero(retail_valor($fila,['COSTO','COSTO_TOTAL'])):null,retail_valor($fila,['CANAL']),$importacionId,$fuente]);}
        else throw new InvalidArgumentException('Dataset retail no reconocido.');$stats['importadas']++;
    }catch(Throwable $e){$stats['errores']++;retail_error($pdo,$importacionId,$tipo,$hoja,$n,$e->getMessage(),$fila);}}
}

function retail_leer_csv(string $ruta):array{
    $h=fopen($ruta,'rb');if(!$h)throw new RuntimeException('No se pudo leer el CSV.');$primera=(string)fgets($h);rewind($h);$delimitadores=[';'=>substr_count($primera,';'),','=>substr_count($primera,','),"\t"=>substr_count($primera,"\t")];arsort($delimitadores);$delim=(string)array_key_first($delimitadores);$filas=[];while(($r=fgetcsv($h,0,$delim))!==false){if(isset($r[0]))$r[0]=preg_replace('/^\xEF\xBB\xBF/','',$r[0]);$filas[]=$r;}fclose($h);return retail_filas_asociativas($filas);
}
function retail_tipo_hoja(string $nombre):?string{$n=retail_normalizar_cabecera($nombre);if(str_contains($n,'VENT'))return 'VENTAS';if(str_contains($n,'EXIST')||str_contains($n,'STOCK'))return 'EXISTENCIAS';if(str_contains($n,'PRODUCT')||str_contains($n,'MAESTRO_ITEM'))return 'PRODUCTOS';return null;}

function retail_importar_archivo(PDO $pdo,string $ruta,string $nombre,string $tipoCsv,array $actor):array{
    $ext=strtolower(pathinfo($nombre,PATHINFO_EXTENSION));$hashArchivo=hash_file('sha256',$ruta);$checksum=$ext==='csv'?hash('sha256',$hashArchivo.'|'.strtoupper($tipoCsv)):$hashArchivo;$q=$pdo->prepare('SELECT * FROM retail_importaciones WHERE checksum=?');$q->execute([$checksum]);if($x=$q->fetch(PDO::FETCH_ASSOC))return ['duplicada'=>true,'importacion'=>$x];
    $pdo->prepare("INSERT INTO retail_importaciones(checksum,archivo,tipo,importado_por)VALUES(?,?,?,?)")->execute([$checksum,$nombre,$ext==='csv'?strtoupper($tipoCsv):'XLSX',$actor['nombre']]);$id=(int)$pdo->lastInsertId();$stats=['leidas'=>0,'importadas'=>0,'errores'=>0];
    try{$pdo->beginTransaction();if($ext==='csv'){$tipo=strtoupper($tipoCsv);if(!in_array($tipo,['PRODUCTOS','EXISTENCIAS','VENTAS'],true))throw new InvalidArgumentException('Selecciona el tipo de datos del CSV.');retail_importar_dataset($pdo,$tipo,retail_leer_csv($ruta),$id,'CSV',$nombre,$stats);}elseif($ext==='xlsx'){$coincidencias=0;foreach(xlsx_read_all_sheets($ruta) as $hoja=>$crudo){$tipo=retail_tipo_hoja($hoja);if(!$tipo)continue;$coincidencias++;retail_importar_dataset($pdo,$tipo,retail_filas_asociativas($crudo),$id,$hoja,$nombre,$stats);}if(!$coincidencias)throw new RuntimeException('El XLSX debe incluir hojas PRODUCTOS, EXISTENCIAS o VENTAS.');}else throw new InvalidArgumentException('Solo se admiten archivos CSV o XLSX.');$pdo->commit();$estado=$stats['errores']?'COMPLETADA_CON_ERRORES':'COMPLETADA';$pdo->prepare('UPDATE retail_importaciones SET estado=?,filas_leidas=?,filas_importadas=?,filas_error=?,detalle=?,finalizado_en=CURRENT_TIMESTAMP WHERE id=?')->execute([$estado,$stats['leidas'],$stats['importadas'],$stats['errores'],"{$stats['importadas']} filas aceptadas",$id]);return ['duplicada'=>false,'importacion_id'=>$id]+$stats;
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$pdo->prepare("UPDATE retail_importaciones SET estado='ERROR',detalle=?,finalizado_en=CURRENT_TIMESTAMP WHERE id=?")->execute([$e->getMessage(),$id]);throw $e;}
}

function retail_importar_lote(PDO $pdo,string $sourceId,array $datasets,array $actor):array{
    $checksum=hash('sha256','API|'.$sourceId);$q=$pdo->prepare('SELECT * FROM retail_importaciones WHERE checksum=?');$q->execute([$checksum]);if($x=$q->fetch(PDO::FETCH_ASSOC))return ['duplicada'=>true,'importacion'=>$x];$pdo->prepare("INSERT INTO retail_importaciones(checksum,archivo,tipo,importado_por)VALUES(?,?,'API',?)")->execute([$checksum,$sourceId,$actor['nombre']]);$id=(int)$pdo->lastInsertId();$stats=['leidas'=>0,'importadas'=>0,'errores'=>0];try{$pdo->beginTransaction();foreach(['productos'=>'PRODUCTOS','existencias'=>'EXISTENCIAS','ventas'=>'VENTAS'] as $k=>$tipo)if(!empty($datasets[$k])&&is_array($datasets[$k])){$filas=array_map(function($f){$x=[];foreach((array)$f as $k=>$v)$x[retail_normalizar_cabecera((string)$k)]=$v;return $x;},$datasets[$k]);retail_importar_dataset($pdo,$tipo,$filas,$id,'API',$sourceId,$stats);}$pdo->commit();$estado=$stats['errores']?'COMPLETADA_CON_ERRORES':'COMPLETADA';$pdo->prepare('UPDATE retail_importaciones SET estado=?,filas_leidas=?,filas_importadas=?,filas_error=?,finalizado_en=CURRENT_TIMESTAMP WHERE id=?')->execute([$estado,$stats['leidas'],$stats['importadas'],$stats['errores'],$id]);return ['duplicada'=>false,'importacion_id'=>$id]+$stats;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$pdo->prepare("UPDATE retail_importaciones SET estado='ERROR',detalle=?,finalizado_en=CURRENT_TIMESTAMP WHERE id=?")->execute([$e->getMessage(),$id]);throw $e;}
}

function retail_config(PDO $pdo,string $clave,int $default):int{$q=$pdo->prepare('SELECT valor FROM config_general WHERE clave=?');$q->execute([$clave]);$v=$q->fetchColumn();return $v===false?$default:max(1,(int)$v);}
function retail_analitica(PDO $pdo,?string $sede=null):array{
    $corte=$pdo->query("SELECT MAX(fecha) FROM (SELECT MAX(fecha) fecha FROM retail_ventas UNION ALL SELECT MAX(fecha) FROM retail_existencias)")->fetchColumn();if(!$corte)return ['corte'=>null,'filas'=>[],'metricas'=>['stock'=>0,'ventas_28d'=>0,'valor_28d'=>0,'quiebres'=>0,'riesgos'=>0,'sobrestock'=>0,'huecos_talla'=>0]];
    $sql="WITH ultima AS(SELECT sku,sede_codigo,MAX(fecha) fecha FROM retail_existencias GROUP BY sku,sede_codigo) SELECT p.sku,p.referencia,p.descripcion,p.categoria,p.color,p.talla,e.sede_codigo,e.sede_nombre,e.unidades stock,COALESCE(SUM(CASE WHEN v.fecha BETWEEN date(?,'-27 days') AND ? THEN v.unidades ELSE 0 END),0) ventas_28d,COALESCE(SUM(CASE WHEN v.fecha BETWEEN date(?,'-27 days') AND ? THEN v.valor_neto ELSE 0 END),0) valor_28d FROM ultima u JOIN retail_existencias e ON e.sku=u.sku AND e.sede_codigo=u.sede_codigo AND e.fecha=u.fecha JOIN retail_productos p ON p.sku=e.sku LEFT JOIN retail_ventas v ON v.sku=e.sku AND v.sede_codigo=e.sede_codigo";$args=[$corte,$corte,$corte,$corte];if($sede){$sql.=' WHERE e.sede_codigo=?';$args[]=$sede;}$sql.=' GROUP BY p.sku,e.sede_codigo ORDER BY valor_28d DESC,ventas_28d DESC';$q=$pdo->prepare($sql);$q->execute($args);$filas=$q->fetchAll(PDO::FETCH_ASSOC);$lead=retail_config($pdo,'RETAIL_LEAD_TIME_DIAS',14);$over=retail_config($pdo,'RETAIL_SOBRESTOCK_DIAS',60);$m=['stock'=>0,'ventas_28d'=>0,'valor_28d'=>0,'quiebres'=>0,'riesgos'=>0,'sobrestock'=>0,'huecos_talla'=>0];$grupos=[];
    foreach($filas as &$f){$stock=(float)$f['stock'];$ventas=(float)$f['ventas_28d'];$diaria=$ventas/28;$cobertura=$diaria>0?$stock/$diaria:null;$f['venta_diaria']=$diaria;$f['cobertura_dias']=$cobertura;$f['sell_through']=($ventas+max(0,$stock))>0?$ventas/($ventas+max(0,$stock)):0;if($stock<=0&&$ventas>0){$f['estado']='QUIEBRE';$m['quiebres']++;}elseif($diaria>0&&$cobertura<$lead){$f['estado']='RIESGO';$m['riesgos']++;}elseif($stock>0&&$ventas<=0){$f['estado']='SIN_ROTACION';$m['sobrestock']++;}elseif($cobertura!==null&&$cobertura>$over){$f['estado']='SOBRESTOCK';$m['sobrestock']++;}else$f['estado']='SALUDABLE';$grupo=($f['referencia']?:$f['sku']).'|'.$f['sede_codigo'];$grupos[$grupo]['positivo']=($grupos[$grupo]['positivo']??false)||$stock>0;$m['stock']+=$stock;$m['ventas_28d']+=$ventas;$m['valor_28d']+=(float)$f['valor_28d'];}unset($f);
    foreach($filas as &$f){$grupo=($f['referencia']?:$f['sku']).'|'.$f['sede_codigo'];if($f['estado']==='SALUDABLE'&&(float)$f['stock']<=0&&!empty($grupos[$grupo]['positivo'])&&trim((string)$f['talla'])!==''){$f['estado']='HUECO_TALLA';$m['huecos_talla']++;}}unset($f);return ['corte'=>$corte,'filas'=>$filas,'metricas'=>$m,'lead_time'=>$lead,'sobrestock_dias'=>$over];
}
