<?php
require_once __DIR__.'/retail_analytics.php';

function siesa_integracion_path():string{return private_path('siesa_integracion.json');}
function siesa_integracion_defaults():array{return ['modo'=>'API_REST','habilitado'=>false,'confirmado_oficial'=>false,'base_url'=>'','token_url'=>'','auth_type'=>'OAUTH2_CLIENT_CREDENTIALS','client_id'=>'','client_secret'=>'','scope'=>'','bearer_token'=>'','api_key_header'=>'X-API-Key','api_key'=>'','health_path'=>'','productos_path'=>'','existencias_path'=>'','ventas_path'=>'','intervalo_minutos'=>60];}
function siesa_integracion_config():array{return array_replace(siesa_integracion_defaults(),leer_config_json(siesa_integracion_path())?:[]);}
function siesa_ruta_valida(string $ruta):bool{return $ruta===''||(!preg_match('#^https?://#i',$ruta)&&!str_contains($ruta,'..')&&str_starts_with($ruta,'/'));}
function siesa_integracion_guardar(array $datos):array{
    $actual=siesa_integracion_config();$modo=strtoupper((string)($datos['modo']??'API_REST'));$auth=strtoupper((string)($datos['auth_type']??'OAUTH2_CLIENT_CREDENTIALS'));if(!in_array($modo,['API_REST','N8N','ARCHIVOS'],true))throw new InvalidArgumentException('Modo de integración inválido.');if(!in_array($auth,['OAUTH2_CLIENT_CREDENTIALS','BEARER','API_KEY'],true))throw new InvalidArgumentException('Autenticación inválida.');
    $base=rtrim(trim((string)($datos['base_url']??'')),'/');$token=trim((string)($datos['token_url']??''));if($modo==='API_REST'&&$base!==''&&!str_starts_with(strtolower($base),'https://'))throw new InvalidArgumentException('La URL base oficial debe usar HTTPS.');if($token!==''&&!str_starts_with(strtolower($token),'https://'))throw new InvalidArgumentException('La URL de token debe usar HTTPS.');
    $rutas=[];foreach(['health_path','productos_path','existencias_path','ventas_path'] as $k){$rutas[$k]=trim((string)($datos[$k]??''));if(!siesa_ruta_valida($rutas[$k]))throw new InvalidArgumentException("{$k} debe ser una ruta relativa que comience por /.");}
    $header=trim((string)($datos['api_key_header']??'X-API-Key'));if(!preg_match('/^[A-Za-z0-9-]{1,60}$/',$header))throw new InvalidArgumentException('Nombre de cabecera API inválido.');
    $cfg=['modo'=>$modo,'habilitado'=>!empty($datos['habilitado']),'confirmado_oficial'=>!empty($datos['confirmado_oficial']),'base_url'=>$base,'token_url'=>$token,'auth_type'=>$auth,'client_id'=>trim((string)($datos['client_id']??'')),'client_secret'=>trim((string)($datos['client_secret']??''))?:$actual['client_secret'],'scope'=>trim((string)($datos['scope']??'')),'bearer_token'=>trim((string)($datos['bearer_token']??''))?:$actual['bearer_token'],'api_key_header'=>$header,'api_key'=>trim((string)($datos['api_key']??''))?:$actual['api_key'],'intervalo_minutos'=>min(1440,max(15,(int)($datos['intervalo_minutos']??60)))]+$rutas;
    if($cfg['habilitado']&&!$cfg['confirmado_oficial'])throw new RuntimeException('Confirma primero que Siesa o su partner autorizó esta integración.');guardar_config_json(siesa_integracion_path(),$cfg);return $cfg;
}
function siesa_integracion_lista(array $a):array{if(array_is_list($a))return $a;foreach(['data','value','items','results'] as $k)if(isset($a[$k])&&is_array($a[$k]))return $a[$k];throw new RuntimeException('La respuesta no contiene una lista reconocible. Se necesita el contrato de respuesta de Siesa.');}

class SiesaConnector{
    private array $cfg;private ?string $token=null;
    public function __construct(array $cfg){$this->cfg=$cfg;}
    private function curl(string $url,string $metodo='GET',$cuerpo=null,array $headers=[]):array{$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$metodo,CURLOPT_HTTPHEADER=>$headers,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>45,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_MAXREDIRS=>0]);if($cuerpo!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,$cuerpo);$body=curl_exec($ch);if($body===false){$e=curl_error($ch);curl_close($ch);throw new RuntimeException('No se pudo contactar el endpoint autorizado de Siesa: '.$e);}$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$type=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE);curl_close($ch);if($code<200||$code>=300)throw new RuntimeException("Siesa respondió HTTP {$code}.");return ['code'=>$code,'body'=>(string)$body,'content_type'=>$type];}
    private function token():string{if($this->token!==null)return $this->token;$tipo=$this->cfg['auth_type'];if($tipo==='BEARER')return $this->token=(string)$this->cfg['bearer_token'];if($tipo==='API_KEY')return $this->token='';if(empty($this->cfg['token_url'])||empty($this->cfg['client_id'])||empty($this->cfg['client_secret']))throw new RuntimeException('Faltan token URL, client ID o client secret entregados por Siesa.');$body=['grant_type'=>'client_credentials','client_id'=>$this->cfg['client_id'],'client_secret'=>$this->cfg['client_secret']];if($this->cfg['scope']!=='')$body['scope']=$this->cfg['scope'];$r=$this->curl($this->cfg['token_url'],'POST',http_build_query($body),['Accept: application/json','Content-Type: application/x-www-form-urlencoded']);$d=json_decode($r['body'],true);if(!is_array($d)||empty($d['access_token']))throw new RuntimeException('El servidor de autorización no devolvió access_token.');return $this->token=(string)$d['access_token'];}
    private function headers():array{$h=['Accept: application/json'];if($this->cfg['auth_type']==='API_KEY'){$h[]=$this->cfg['api_key_header'].': '.$this->cfg['api_key'];}else{$t=$this->token();if($t==='')throw new RuntimeException('La credencial de acceso está vacía.');$h[]='Authorization: Bearer '.$t;}return $h;}
    public function obtener(string $ruta):array{if(!siesa_ruta_valida($ruta)||$ruta==='')throw new InvalidArgumentException('Endpoint Siesa inválido.');$r=$this->curl($this->cfg['base_url'].$ruta,'GET',null,$this->headers());$d=json_decode($r['body'],true);if(!is_array($d))throw new RuntimeException('Siesa no devolvió JSON válido.');return $d;}
    public function probar():array{if(empty($this->cfg['confirmado_oficial']))throw new RuntimeException('La conexión no está marcada como autorizada por Siesa.');if($this->cfg['auth_type']==='OAUTH2_CLIENT_CREDENTIALS')$this->token();if($this->cfg['health_path']==='')return ['ok'=>true,'codigo'=>null,'mensaje'=>'Autenticación preparada. Falta la ruta de diagnóstico oficial para probar lectura.'];$this->obtener($this->cfg['health_path']);return ['ok'=>true,'codigo'=>200,'mensaje'=>'Autenticación y endpoint de diagnóstico respondieron correctamente.'];}
}

function siesa_log_iniciar(PDO $pdo,string $accion,string $modo,string $actor,string $correlacion):int{$pdo->prepare('INSERT INTO siesa_integracion_log(correlacion,accion,modo,iniciado_por)VALUES(?,?,?,?)')->execute([$correlacion,$accion,$modo,$actor]);return (int)$pdo->lastInsertId();}
function siesa_log_finalizar(PDO $pdo,int $id,string $estado,string $resumen,array $detalle=[],?int $codigo=null):void{$pdo->prepare('UPDATE siesa_integracion_log SET estado=?,codigo_http=?,resumen=?,detalle_json=?,finalizado_en=CURRENT_TIMESTAMP WHERE id=?')->execute([$estado,$codigo,$resumen,json_encode($detalle,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$id]);}
function siesa_probar_conexion(PDO $pdo,array $actor):array{$cfg=siesa_integracion_config();if($cfg['modo']!=='API_REST')throw new RuntimeException('La prueba directa aplica solamente al modo API REST.');$corr='test-'.gmdate('YmdHis').'-'.bin2hex(random_bytes(2));$id=siesa_log_iniciar($pdo,'PRUEBA',$cfg['modo'],$actor['nombre'],$corr);try{$r=(new SiesaConnector($cfg))->probar();siesa_log_finalizar($pdo,$id,'COMPLETADA',$r['mensaje'],[],$r['codigo']);return $r;}catch(Throwable $e){siesa_log_finalizar($pdo,$id,'ERROR',$e->getMessage());throw $e;}}
function siesa_sincronizar(PDO $pdo,array $actor,?string $correlacion=null):array{
    $cfg=siesa_integracion_config();if($cfg['modo']!=='API_REST'||empty($cfg['habilitado'])||empty($cfg['confirmado_oficial']))throw new RuntimeException('La sincronización API de Siesa no está habilitada y autorizada.');$corr=$correlacion?:'sync-'.gmdate('YmdHi');$q=$pdo->prepare('SELECT * FROM siesa_integracion_log WHERE correlacion=?');$q->execute([$corr]);if($x=$q->fetch(PDO::FETCH_ASSOC))return ['ok'=>$x['estado']==='COMPLETADA','duplicada'=>true,'resumen'=>$x['resumen']];$id=siesa_log_iniciar($pdo,'SINCRONIZACION',$cfg['modo'],$actor['nombre'],$corr);try{$client=new SiesaConnector($cfg);$datasets=[];foreach(['productos'=>'productos_path','existencias'=>'existencias_path','ventas'=>'ventas_path'] as $k=>$campo)if($cfg[$campo]!=='')$datasets[$k]=siesa_integracion_lista($client->obtener($cfg[$campo]));if(!$datasets)throw new RuntimeException('Configura al menos un endpoint de lectura entregado por Siesa.');$r=retail_importar_lote($pdo,'siesa-api-'.$corr,$datasets,$actor);$resumen="{$r['importadas']} filas importadas; {$r['errores']} con observaciones";siesa_log_finalizar($pdo,$id,'COMPLETADA',$resumen,['importacion_id'=>$r['importacion_id']??null,'filas'=>$r['leidas']??0]);return ['ok'=>true,'duplicada'=>false,'resumen'=>$resumen]+$r;}catch(Throwable $e){siesa_log_finalizar($pdo,$id,'ERROR',$e->getMessage());throw $e;}
}
function siesa_sincronizar_programada(PDO $pdo):?array{$cfg=siesa_integracion_config();if($cfg['modo']!=='API_REST'||empty($cfg['habilitado'])||empty($cfg['confirmado_oficial']))return null;$q=$pdo->query("SELECT finalizado_en FROM siesa_integracion_log WHERE accion='SINCRONIZACION' AND estado='COMPLETADA' ORDER BY id DESC LIMIT 1");$ultima=$q->fetchColumn();if($ultima&&strtotime((string)$ultima)>time()-((int)$cfg['intervalo_minutos']*60))return null;return siesa_sincronizar($pdo,['nombre'=>'Tarea programada'],'auto-'.gmdate('YmdHi'));}
